bq_evo:
  outputs:
    dev:
      dataset: test_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west3
      method: oauth-secrets
      refresh_token: "{{ env_var('secrets.BQ_TOKEN') }}"
      client_id: "{{ env_var('secrets.BQ_CLIENTID') }}"
      client_secret: "{{ env_var('secrets.BQ_CLIENTSECRET') }}"
      token_uri: "{{ env_var('secrets.BQ_TOKENURI') }}"
      priority: interactive
      project: oss-big-query-dashboard-prod
      threads: 4
      type: bigquery
  target: dev