version: 2

models:
#Google Ads
  - name: mrt_google_ads_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Bing Ads
  - name: mrt_bing_ads_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Google Analytics
  - name: mrt_google_analytics_campaign_webperformance
    description: Enthält grundlegende Web-Performancewerte aller über GA4 erfassten Kampagnen.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
  - name: mrt_google_analytics_NDG_merged_ua_ga4_conversions_summarized
    description: |
      Enthält alle Conversiondaten bis einschl. 04.06.2023 aus Unisversal Analytics, alle Conversions ab 05.06.2023 aus Google Analytics 4.
      Das Zielvorhaben 'contact_form_button' ist hier nur für die Landingpage evo-ag.de/pv-aktion gefiltert.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
  - name: mrt_google_analytics_merged_ua_ga4_transactions_summarized
    description: Enthält alle aggregierten Transaktionen bis einschl. 04.06.2023 aus Unisversal Analytics, alle Conversions ab 05.06.2023 aus Google Analytics 4. Enthält keine Detailinformationen je Transaktion.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Meta
  - name: mrt_meta_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null

#Linkedin
  - name: mrt_linkedin_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null

#Multi-Source_Models
  - name: mrt_metainformation_campaigns
    description: Enthält Kampagnen aus allen Quelldatensystemen mit Metainformationen.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null 
      - name: IsPaid
        description: true = bezahlte Kampagne 
