version: 2

models:
#Google Ads
  - name: mrt_google_ads_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Bing Ads
  - name: mrt_bing_ads_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Google Analytics
  - name: mrt_google_analytics_campaign_webperformance
    description: Enthält grundlegende Web-Performancewerte aller über GA4 erfassten Kampagnen.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null
  - name: mrt_google_analytics_NDG_merged_ua_ga4_conversions_summarized
    description: |
      Enthält alle Conversiondaten bis einschl. 04.06.2023 aus Unisversal Analytics, alle Conversions ab 05.06.2023 aus Google Analytics 4.
      Das Zielvorhaben 'contact_form_button' ist hier nur für die Landingpage evo-ag.de/pv-aktion gefiltert.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
  - name: mrt_google_analytics_merged_ua_ga4_transactions_summarized
    description: Enthält alle aggregierten Transaktionen bis einschl. 04.06.2023 aus Unisversal Analytics, alle Conversions ab 05.06.2023 aus Google Analytics 4. Enthält keine Detailinformationen je Transaktion.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
      - name: Keyword
        description: '{{ doc("keyword") }}'
      - name: KeywordMatchType
        description: '{{ doc("KeywordMatchType") }}'
#Meta
  - name: mrt_meta_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null

#Linkedin
  - name: mrt_linkedin_basic_campaign_stats
    description: '{{ doc("performancereporting_stats") }}'
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null

#Multi-Source_Models
  - name: mrt_metainformation_campaigns
    description: Enthält Kampagnen aus allen Quelldatensystemen mit Metainformationen.
    columns:
      - name: CampaignID
        description: '{{ doc("campaignID") }}'
        tests:
          - not_null 
      - name: Campaign
        description: '{{ doc("campaign_name") }}'
      - name: Medium
        description: '{{ doc("source_medium_manual") }}'
      - name: Source
        description: '{{ doc("source_medium_manual") }}'
      - name: IsPaid
        description: true = bezahlte Kampagne
      - name: Kampagenenkategorie
        description: Brand = Suchkampagnen mit Markenbegriffen, Generisch = Alle Kampagnen, die nicht Brand sind (insb. Suchkampagnen mit generischen Suchbegriffen).
      - name: Kampagnenprodukt
        description: Grobe Differenzierung der durch die Kampagnen beworbenen Produkte.
      - name: Produktkategorie
        description: Eine Hierachiebene tiefer als Kampagnenprodukt. Für Strom/Gas = Differenzierung nach Strom, Gas, Heizstrom (wenn zutreffend), für Recruiting = Ausbildung oder Sonstige
      - name: Kampagnenbetreuer
        description: Ansprechpartner (Unternehmen) für die Kampagne. Exakte Zuordnung siehe Quelltext.
      - name: Stellen_ID
        description: Nur relevant für Recruiting-Kampagnen. Differenzierung der jeweils in den Kampagnen beworbenen Stellen auf Basis der Kampagnenbezeichnungen. Zuordnung erfolgt manuell.
      - name: Gebiet
        description: Vermarktungsgebiet der Kampagne gemäß Kampagnenbezeichnung. Insbesondere relevant für Paid-Vermarktung.
      - name: Gebiet_clustered
        description: Gruppierte Variante der Spalte Gebiet. Differenziert nur noch Stammgebiet und OOA.
      - name: Werbenetzwerk
        description: Netzwerk, in dem die Kampagne ausgespielt wurde. Basiert auf den Spalten "Campaign" & "Source".
  - name: mrt_zielvorhaben_uebersicht_NDG
    description: Enthält eine Übersicht aller verwendeten Conversionaktionen von NDG.
    columns:
      - name: Partner
        description: '{{ doc("Partner") }}'
      - name: ZielvorhabenID
        description: ID aus ZielvorhabenName & Partner
      - name: ZielvorhabenName
        description: Bezeichnung des Zielvorhabens bzw. entspricht dem GA4 Ereignis
      - name: KategorieZielvorhaben
        description: Clustert die unterschiedlichen Conversion-Ereignisse. Genutzt, um bei Kampagnen mit mehreren Conversionereignissen entsprechend alle Conversions bei der Performancebewertung zu berücksichtigen.
