name: "dbt dev pipeline"

on:
  push:
  workflow_dispatch:

env:
  ENV_CODE: ${{ vars.ENV_CODE }}
  PROJ_CODE: ${{ vars.PROJ_CODE }}
  BQ_ACCOUNT: ${{ secrets.BQ_ACCOUNT }}
  BQ_PWD: ${{ secrets.BQ_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: "Step 00 - Prüfe Version"
        run: node --version
      - name: "Step 01 - Checkout current branch"
        id: step-01
        uses: actions/checkout@v3